version: '3.8'

services:
  mongodb:
    image: mongo  # Use the official MongoDB image
    ports:
      - "27017:27017"  # Expose port 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin  # Set the root username
      MONGO_INITDB_ROOT_PASSWORD: password  # Set the root password
    volumes:
      - mongo-data:/data/db  # Persist MongoDB data to a volume
    networks:
      - mongo-network  # Connect to a custom network

networks:
  mongo-network:
    driver: bridge  # Use the bridge network driver

volumes:
  mongo-data:
    driver: local  # Use the local volume driver for persistence
